### ISSUE TITLE
tensorflow issue on python3.5 running at raspbian 9 stretch

### ISSUE THREAD

**Issue by LuisR69** [meshy/pythonwheels#107]
Thonny shell log reports a runtime warning while executing "import tensorflow" instruction: compile version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5

**Comment by meshy** [comment]
@LuisR69 – as per the website:

>    This is not the official website for wheels, just a nice visual way to measure adoption.

**Comment by meshy** [comment]
The best place to open an issue might be: https://github.com/tensorflow/tensorflow/issues

**Comment by LuisR69** [comment]
Thanks for your advice.
Best regards.
