### ISSUE TITLE
arm64 wheels

### ISSUE THREAD

**Issue by vielmetti** [meshy/pythonwheels#109]
I have a report from @notafile at https://github.com/WorksOnArm/cluster/issues/116#issuecomment-463818754 that there are no wheels for arm64.

> The problem of wheels is that there is no PEP specification for linux ARM wheels. The manylinux1 and manylinux2010 platform tags only apply to x86(_64), due to being based on Centos7, which does not support anything else. So before any wheels could be uploaded, a manylinux standard for ARM would be required.

The result of this is that packages that have a lot of dependencies build slowly on arm64.

**Comment by vielmetti** [comment]
And I realize that this problem may not be resolvable in this repository, but i don't know exactly where to go upstream to address it!

**Comment by NotAFile** [comment]
The relevant issues here are:

https://github.com/pypa/manylinux/issues/84
https://github.com/pypa/warehouse/issues/3668

**Comment by vielmetti** [comment]
Closing in favor of the upstream issues.
