### ISSUE TITLE
dlib wheel for linux

### ISSUE THREAD

**Issue by tensor-buddy** [meshy/pythonwheels#110]
Is there a dlib (machine-learning) wheel for linux?

**Comment by meshy** [comment]
Hello! You've found yourself on the wrong github repository! This repo is for managing the https://pythonwheels.com website. Don't worry -- you're not the first to make this mistake.

In this case, you're looking for https://github.com/davisking/dlib

FYI, you can see what downloads are available for `dlib` on its "downloads" page on PyPI: https://pypi.org/project/dlib/#files

**Comment by meshy** [comment]
oh, and I notice you've just signed up to Github... welcome! :smile:
