### ISSUE TITLE
does it support setup.py with other requirement modules.

### ISSUE THREAD

**Issue by vnitinv** [meshy/pythonwheels#52]
My module is dependent on other modules, which are mentioned in setup.py as requirements.
Can i create a wheel for my module even if required modules is not wheel.

**Comment by ghickman** [comment]
@vnitinv – your question sounds like you're asking about the wheel format itself, unfortunately this project is for the informational site http://pythonwheels.com, sorry about the confusion!

The wheel project lives [here](https://bitbucket.org/pypa/wheel/issues) and pypa channel on irc.freenode.org is very good for finding answers this type of question. I hope this helps you find an answer to your question and again sorry for the confusion.
