### ISSUE TITLE
Favicon url returns a 403

### ISSUE THREAD

**Issue by ghickman** [meshy/pythonwheels#55]
http://pythonwheels.com/favicon.ico

There isn't a favicon in the repo so it's either been lost to the mists of time or there never was one.

Should we add one or should we remove the link?

**Comment by meshy** [comment]
Hey dude `:)` thanks for the report.

I don't think that there ever was one. It'd be nice for it to be a green circle `.ico`, but maybe we could get fancy, and try to create one to reflect the current state of the wheel.

I can imagine that happening in one of two ways:
- we could generate it using canvas (client-side) on page load
- we could generate it (somehow) on server-side as part of the update script

It's a shame we can't use the existing svg, as there seems to be [very low browser support](http://caniuse.com/#feat=link-icon-svg) for that.

**Comment by ghickman** [comment]
@meshy – both good ideas, I vote for the green circle as a first step and then enhancement $later to the fancy generated one.

**Comment by meshy** [comment]
Sounds good to me `:)`

**Comment by meshy** [comment]
[inkscape](http://stackoverflow.com/a/14174624/400691) and [favico.js](http://lab.ejci.net/favico.js/) might both be worth investigating, as browser support (as yet) remains low.

**Comment by hugovk** [comment]
First step in PR #https://github.com/meshy/pythonwheels/pull/79.

**Comment by ghickman** [comment]
Closing with many thanks to @hugovk!
