### ISSUE TITLE
Website painstakingly slow

### ISSUE THREAD

**Issue by pguth** [meshy/pythonwheels#61]
Page only loads half - from Stuttgart, Germany.

... maybe switch to [Github Pages](https://help.github.com/categories/github-pages-basics/)?

**Comment by meshy** [comment]
Hm strange -- I don't get this behaviour.

It's hosted on S3, so I'm not sure if github pages will make a big difference. Do you have javascript disabled, or perhaps you're getting JS errors in your console?

**Comment by ghickman** [comment]
Same here (although @meshy and I are both UK based).

It's also pushed out to cloudfront (backed with S3) to add to @meshy's answer. Could you a screenshot of your network tab for us as well please?

**Comment by ghickman** [comment]
To add to @meshy's answer again: CloudFront and GitHub Pages are both CDNs so a change there is unlikely to make a huge difference and this could possibly be your local CF PoP having an issue.

**Comment by dtran320** [comment]
The page appears to load fine functionally, but perhaps what @pguth was referring to is that it says in "Connecting" status for a good full minute before finally timing out for `badge.svg`, at least for me from San Francisco, CA using Chrome Version 44.0.2403.125 (64-bit).

Stuck in "Connecting":
![screenshot 2015-08-03 17 02 34](https://cloud.githubusercontent.com/assets/177059/9050341/c3c220c8-3a01-11e5-80f0-5e8892371695.png)

`badge.svg` is still pending (`favicon.ico` and `ga.js` also appear to be problematic)
![screenshot 2015-08-03 17 02 39](https://cloud.githubusercontent.com/assets/177059/9050378/f983d7c4-3a01-11e5-8380-e0619e36bf91.png)

Finally times out after 59.94s:
![screenshot 2015-08-03 17 04 44](https://cloud.githubusercontent.com/assets/177059/9050383/000730f0-3a02-11e5-8443-21be9c885079.png)

**Comment by meshy** [comment]
The broken link has now been removed. Thanks for reporting!

**Comment by dtran320** [comment]
:+1:
