### ISSUE TITLE
How to install wheel with a mouse doubleclick

### ISSUE THREAD

**Issue by axil** [meshy/pythonwheels#66]
I would add the instructions here or maybe include this into the pip distributive unless it is already there:

The following two commands can be run in command line under administrator privileges:
```
assoc .whl=pythonwheel
ftype pythonwheel=cmd /c "pip.exe install %1 & pause"
```
Alternatively, they can be copied into a `wheel.bat` file and executed with 'Run as administrator' checkbox in the properties.

PS pip.exe is assumed to be in the PATH.

**Comment by meshy** [comment]
Hi @axil, `pythonwheels.com` is simply an informative site showing you how many projects provide wheels, and should not be considered to be the official documentation. Instructions on how to install them fall outside of our remit, and should instead be found there.

You can find the official documentation at https://packaging.python.org.
