### ISSUE TITLE
lxml is avaliable

### ISSUE THREAD

**Issue by ololoe** [meshy/pythonwheels#67]
lxml supports wheel

**Comment by meshy** [comment]
Thanks again, @ololoe. As explained in #68, the contents of this website are largely automatic.

In the case of lxml, it seems as though (at time of writing) the maintainer has uploaded wheels for version 3.4.4, but not the latest version (which is what we check against). Perhaps it would be best to contact the maintainer of that package, and see if they are available to upload the wheels for the new version.

I hope you don't mind me closing this issue, as it seems to me that pythonwheels.com is acting as expected under the circumstances.
