### ISSUE TITLE
pycrypto

### ISSUE THREAD

**Issue by ololoe** [meshy/pythonwheels#68]
PyCrypto is dead, but pycryptodome - backwards compatible fork of pycrpypto - supports wheel.

**Comment by meshy** [comment]
Hi @ololoe, thanks for the reports.

The pythonwheels.com website updates automatically once an hour, collecting and displaying information about the top 360 most downloaded packages from PyPI. In that update it will check to see if each package has any wheel packages, and make them green if appropriate.

In time, dead projects should fall to the bottom and drop the list and, as pycrypodome gets more downloads, we should see it appear and rise.

I hope you don't mind me closing this issue until we await its appearance `:)`
