### ISSUE TITLE
logilab package updates

### ISSUE THREAD

**Issue by hiccup7** [meshy/pythonwheels#69]
According to http://www.astroid.org/, "Astroid is the new name for the former logilab-astng python package, the core of the pylint code checker."
astroid is already on http://pythonwheels.com/, so I suggest removing logilab-astng.

Astroid now has dependencies of wrapt and lazy-object-proxy packages instead of logilab-common.
See https://www.mail-archive.com/gentoo-commits@lists.gentoo.org/msg171521.html
wrapt is already on http://pythonwheels.com/, but lazy-object-proxy is not.  I suggest adding lazy-object-proxy (already supports wheels) and removing the deprecated logilab-common from http://pythonwheels.com/

I also suggest adding pylint (already supports wheels) to http://pythonwheels.com/

**Comment by ghickman** [comment]
Hi @hiccup7, thanks for your interest in Python Wheels!

As noted in the [What is this list?](http://pythonwheels.com/#about-list) section of the website Python Wheels only lists the top 360 most-downloaded packages on PyPI. We do not manually add packages to the website.
