### ISSUE TITLE
Packages (e.g., gevent, numpy) are green if they have wheels for some but not all operating systems

### ISSUE THREAD

**Issue by snakescott** [meshy/pythonwheels#70]
gevent is listed as offering a wheel, but it only offers wheels for Windows and OSX, not Linux.

**Comment by meshy** [comment]
Thanks for the report -- this has come up in a couple of variations before. See #2 and #48

**Comment by snakescott** [comment]
Ah, thanks, those issues are informative, I've edited my issue title to try to help avoid dupes -- I skimmed the repo issues before filing, but obviously didn't look close enough!

**Comment by meshy** [comment]
Glad to be able to help. Thanks for renaming the issue `:)`

**Comment by ghickman** [comment]
PyPI now allows Linux wheels to be uploaded (the `manylinux` variant) so I think this issue is now fixed/defunct?

@snakescott, @meshy – please reopen if you disagree :)
