### ISSUE TITLE
[wheel] vs [bdist_wheel]

### ISSUE THREAD

**Issue by mahmoud** [meshy/pythonwheels#71]
Hey there! Very nice site, just a quick qualm: @hynek guide says to use `[wheel]` as the section in setup.cfg, but the pythonwheels.com site says use `[bdist_wheel]`. Which is the canonical way?

**Comment by ghickman** [comment]
@mahmoud – it's `[bdist_wheel]` (as per the [docs](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#universal-wheels)), but in fairness to @hynek it was originally `[wheel]`!

**Comment by meshy** [comment]
Related to https://github.com/meshy/pythonwheels/pull/41
