### ISSUE TITLE
LDA wheel 

### ISSUE THREAD

**Issue by ravsh16** [meshy/pythonwheels#72]
I could not install LDA wheel which is available on PyPi. The wheel is not indexed on pythonwheel.com. Kindly provide a clean compiled version of LDA for Windows 7 64 bit. 

TIA

**Comment by meshy** [comment]
Hi @ravsh16 unfortunately pythonwheels.com is simply an informative site showing you how many projects provide wheels. It doesn't have any control over those projects or the wheels they provide.

However, I see [LDA is open source](https://github.com/ariddell/lda/) so you may be able to contact the author(s) and offer your help in providing a wheel for their project.

**Comment by ravsh16** [comment]
Hi @meshy, 

Thanks so much for replying. Finally, I got it done by changing the default Visual Basics needed to compile python source. 

https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

**Comment by meshy** [comment]
Great to hear that you've got it sorted `:)` -- Also, it's great to see `pythonwheels.com` mentioned on a Microsoft tech blog! `:D`

**Comment by ravsh16** [comment]
@meshy Haha. Thanks. 

good going, guys :D
