### ISSUE TITLE
manylinux wheels should be also mentioned on the homepage

### ISSUE THREAD

**Issue by aivarannamaa** [meshy/pythonwheels#75]
Currently it says that wheels are only for Windows and OS X, but PEP 513 https://www.python.org/dev/peps/pep-0513/ should be also mentioned. 

(New Pygame Linux wheels are a nice example how to make complicated installation really easy)

**Comment by meshy** [comment]
Thank you for opening this. This issue has already been dealt with in https://github.com/meshy/pythonwheels/pull/73, but unfortunately, due to https://github.com/meshy/pythonwheels/issues/74 we have not yet been able to push it up.

Sorry about that!

**Comment by meshy** [comment]
#74 has been resolved, so I'm closing this now. Thanks again :)
