### ISSUE TITLE
PyYAML 3.11 supports python 3

### ISSUE THREAD

**Issue by quodlibetor** [meshy/pythonwheels#76]
https://pypi.python.org/pypi/PyYAML

Not sure why it's listed as not supporting py3? It's supported it for a long time.

**Comment by ghickman** [comment]
@quodlibetor – as per the What is this List section:

> This site shows the top 360 most-downloaded packages on PyPI showing which have been uploaded as wheel archives.

Python 2 or 3 compatibility isn't a part of that check.

**Comment by quodlibetor** [comment]
I... was in the zone. Unfortunately it was the wrong zone.
