### ISSUE TITLE
Vague/ambiguous instructions

### ISSUE THREAD

**Issue by arokem** [meshy/pythonwheels#83]
"Create a file called setup.cfg with the following content and upload your package"

Where do I create this file? What steps do I need to do to "upload the package" once I have created this file?

Thanks!

**Comment by ghickman** [comment]
@arokem – your `setup.cfg` goes in the root of your project directory alongside your `setup.py` ([docs](https://packaging.python.org/distributing/#setup-cfg)).

To upload your project to PyPI you can follow the [Python Packaging Guide's instructions](https://packaging.python.org/distributing/#uploading-your-project-to-pypi).

Hope that helps!
