### ISSUE TITLE
Use the module installed by Pip in Eclipse IDE pydev

### ISSUE THREAD

**Issue by bharathkumariplon** [meshy/pythonwheels#87]
How do i use the module which is installed using Pip. I am not able to add as egg whereas there is no option to add an wheel. I have installed kivi using pip but. i am not able to use it like a module installed in eclipse using egg. How do I proceed further

**Comment by ghickman** [comment]
@bharathkumariplon – this is the project powering http://pythonwheels.com/, a data visualisation of wheel provision in the Python ecosystem.  You'll need to ask in the relevant help channels for the projects you're having trouble with.
